export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: May 24, 2026</p>

      <div className="flex flex-col gap-6 text-gray-600 dark:text-gray-300 text-sm leading-relaxed">

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using Charmy ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">2. Description of Service</h2>
          <p>Charmy is an AI-powered application that helps users improve their romantic and social conversations. The App uses artificial intelligence to generate personalized message suggestions based on user-defined relationship goals.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">3. User Accounts</h2>
          <p>You must create an account to use Charmy. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 18 years old to use this service.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">4. Subscriptions and Payments</h2>
          <p>Charmy offers free and premium plans. Premium subscriptions are billed on a monthly or yearly basis. All payments are processed securely through Paddle. By subscribing, you authorize us to charge your payment method on a recurring basis until you cancel.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">5. Cancellation</h2>
          <p>You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period. You will continue to have access to premium features until the end of the period you have paid for.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">6. Acceptable Use</h2>
          <p>You agree not to use Charmy to harass, harm, or manipulate others. The AI-generated suggestions are provided as communication assistance only. You are solely responsible for how you use the content generated by the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">7. Intellectual Property</h2>
          <p>All content, features, and functionality of Charmy are owned by Charmy and are protected by intellectual property laws. You may not copy, modify, or distribute any part of the App without our written permission.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">8. Disclaimer of Warranties</h2>
          <p>Charmy is provided "as is" without warranties of any kind. We do not guarantee that the AI suggestions will result in any particular outcome in your personal relationships. Use the App at your own discretion.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">9. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, Charmy shall not be liable for any indirect, incidental, or consequential damages arising from your use of the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">10. Changes to Terms</h2>
          <p>We reserve the right to update these Terms at any time. We will notify users of significant changes via email or in-app notification. Continued use of the App after changes constitutes acceptance of the new Terms.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">11. Contact</h2>
          <p>For any questions regarding these Terms, please contact us at <a href="mailto:support@charmy.app" className="text-charmy-500">support@charmy.app</a></p>
        </section>

      </div>
    </div>
  )
}