# Generated by Django 6.0.5 on 2026-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='is_premium_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='strategy_explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='context_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='raw_input',
            field=models.TextField(),
        ),
    ]
