# Generated by Django 6.0.5 on 2026-09-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_aisuggestion_is_premium_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisuggestion',
            name='is_premium_only',
        ),
    ]
