# Generated by Django 6.0.5 on 2026-05-17 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contacts/')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('sms', 'SMS'), ('other', 'Autre')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('romantic', 'Amour / Séduction'), ('friendship', 'Amitié'), ('professional', 'Professionnel'), ('family', 'Famille'), ('reconciliation', 'Réconciliation')], max_length=20)),
                ('goal', models.TextField(help_text="Ce que l'utilisateur veut accomplir")),
                ('tone', models.CharField(choices=[('playful', 'Joueur / Humoristique'), ('tender', 'Tendre / Doux'), ('direct', 'Direct / Franc'), ('formal', 'Formel / Pro'), ('flirty', 'Flirty')], default='playful', max_length=20)),
                ('backstory', models.TextField(blank=True, help_text='Historique de la relation')),
                ('health_score', models.IntegerField(default=50)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='relations.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='RelationJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('event_type', models.CharField(choices=[('milestone', 'Étape importante'), ('conflict', 'Conflit'), ('positive', 'Moment positif'), ('note', 'Note libre')], default='note', max_length=20)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='relations.relation')),
            ],
        ),
    ]
