# Generated by Django 6.0.5 on 2026-05-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='strategy',
            field=models.TextField(blank=True, help_text="Approche psychologique : comment l'utilisateur veut se comporter"),
        ),
    ]
