# Generated by Django 6.0.5 on 2026-05-23 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_stripe_customer_id_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='user',
            name='daily_suggestions_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suggestions_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('plan', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel'), ('pack', 'Pack Situations')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré'), ('past_due', 'En retard')], default='active', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
