# Generated by Django 6.0.5 on 2026-09-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_suggestions_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_reset_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suggestions_credits',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
